### PR TITLE
SetThousandsSeparator

### LINKED ISSUE #53: Option for thousands separator
It seems like it would be a good idea to have an option for a thousands separator for floats and ints, which can make structs with many large numbers easier to read. For example: 

```
myStruct{
  myfloat: 1,000,000.00,
}
```

What do you think?

### PR DESCRIPTION
**Pull request by mariusgrigoriu**
Experimenting with a fix #53 

`golfing.org/x/text/message` provides a drop in replacement for `fmt` that can close #53. It seems to be a super clean way of taking care of this and perhaps supporting other localization in the future.

The catch? You get default behavior with `%#v`, but you do get localization with `%d`, `%f`, `%v`, and possibly others. I'm wondering if this could be an acceptable implementation. We could add an option to set the language, and potentially use alternatives to `%#v` as needed similar to what was done in #55.

Does this seem like a reasonable way to go?

### CODE REVIEW

**Comment by k0kubun** [comment]
Using `golang.org/x/text/message` seems like a way to simplify the implementation of the thousands separator.

However, I don't think you need to use the localizedPrinter for everything. To avoid unexpected side effects to non-numbers, please consider leaving the implementation that is not related to numbers as is. You would need to touch it if and only if `SetThousandsSeparator` is used.

**Comment by mariusgrigoriu** [comment]
According to [documentaiton](https://pkg.go.dev/golang.org/x/text/message#hdr-Localized_Formatting), only numbers and certain specialized types are affected by `golang.org/x/text/message`. Also format strings work the same except for the following changes: (not mentioned in the docs is that the `v` verb also uses localized formatting unless accompanied by `#`)
```
- flag # always resorts to fmt for printing
- verb 'f', 'e', 'g', 'd' use localized formatting unless the '#' flag is
  specified.
- verb 'm' inserts a translation of a string argument.
```

The latest commit adds `SetThousandsSeparator(bool)` and uses the localization functions only for the number formats where that might be useful. I added some test cases and attempted to minimize proliferation of if's in func raw(). How does this look to you?

**Comment by k0kubun** [comment]
looks good to me. Thank you! 

Is there anything blocking you to mark this as ready for review? I cannot push the merge button since this is still a draft pull request.

**Comment by mariusgrigoriu** [comment]
No blocking issues!

**Review by k0kubun — APPROVED** [review]
:+1:

**Pull request merged**
