### PR TITLE
Add max depth var

### PR DESCRIPTION
**Pull request by sumerc**
Hey,

I am using this to print out deep structures, to filter out some unnecessary structs.

Just sending maybe you would like to merge it. I have not added tests as I am not sure if this is something you would like to merge.

Thanks,

### CODE REVIEW

**Comment by k0kubun** [comment]
Recently we introduced `PrettyPrinter` struct to avoid defining too many global variables in this library. Could you change the variable to be a field of `PrettyPrinter`? You would still be able to have the same benefit by modifying the field of `defaultPrettyPrinter`.

**Comment by sumerc** [comment]
Done. Do you also prefer to remove `defaultMaxDepth`, too?

**Comment by k0kubun** [comment]
Yes please. Other variables are left just for backward compatibility, and we don't need to define new configs there.

**Comment by sumerc** [comment]
Done.

**Pull request merged**
