### PR TITLE
Add support for customized colors

### PR DESCRIPTION
**Pull request by JanBerktold**
Support for customized colors including the ability to mix font and background colors by using a Flag-based description of the colors.

Any questions, thoughts or feedback? :)

### CODE REVIEW

**Comment by k0kubun** [comment]
Thank you for creating a pull request!

But before reviewing your idea and detail implementation, I have a question. Why did you delete printer_test.go?
It is a very important test to keep backward compatibility. If you want to change this library, you should pass the existing tests.

**Comment by JanBerktold** [comment]
Ooops, completely missed out on that! Sorry!

Will fix this evening.

**Comment by k0kubun** [comment]
> Ooops, completely missed out on that! Sorry!

That's ok. :)

**Comment by JanBerktold** [comment]
All right, found some time:
- I've re-added printer_test.go
- Found & fixed some missed bugs 

However, I've had to change printer_test.go as it previously expected the bold setting after the color and my code did it the other way around. Is that fine?

**Comment by k0kubun** [comment]
> I've re-added printer_test.go

Thank you. I can see this branch's behavior on wercker CI and it looks good.

> However, I've had to change printer_test.go as it previously expected the bold setting after the color and my code did it the other way around. Is that fine?

That's fine. I don't mind the order of bold setting and color.

I'll review this when I have some time to work with, but before reviewing your code, these commits should be squashed into some meaningful groups.
Though I don't still read code well, I can tell this change does not need 17 steps. Could you rebase and squash the commits to make each commit's purpose clear?

For example, aa24aee510334c2d71667faa42271cb8ffe13be3 and ce0234aec23bfe0fb7719cc57510e20323b202d7 should be one commit, 86d5c005506818c32d117ff958aa0f12d8a97c7e has unnecessary changes and 8598b82e5fcaa43b8967fd113e2b83c3e701265f is a too short change.

**Comment by k0kubun** [comment]
I reviewed your feature now. (Sorry for the delay.)
Your feature request looks good and I want to merge this feature. So please reconsider the commits.

**Comment by JanBerktold** [comment]
Attempted to break it down into less commits. Is it fine?

However, (somehow) I've managed to include one of the previous commits. Do you happen to know how I can remove it from my pull request?

**Comment by k0kubun** [comment]
Now this pull request became easier to read. Thank you. :)
But still with some problems.

- e60290543482f91596d5b54fa7fac3949f6733bd's adding `SetColorScheme` and 6132ef4af5522abd60f400217d5afc16d1e419e0's writing `TestColorScheme` should be one commit. If the test is in the commit that includes the change requires it, the test's purpose will be clear.
- 6c3353f639b90557ae100a3204e5ea0ef38a67b1's printer_test deletion is unnecessary. It should be combined into c7fededc4d220af6fae57698485d716145173303's adding printer_test. That's because I want to see the diff of test changes in one commit.
- IMHO, writing contributors should be library author's responsibility, though I have no objection to describe your name as contributors after merging this. :)

> Attempted to break it down into less commits. Is it fine?

Not fine. That's because I can't merge this pull request because of the conflict. You can see the gray mark in this page. It indicates this pull request can't be merged.


Usually you should pull the remote master branch into your local master branch, rebase your topic branch from the master branch and force-push your local topic branch to your remote fork's topic branch.
(First of all, you should create a pull request from non-master branch because sometimes you have to rebase pull request's branch from master branch. For this pull request, I don't mind whether the branch name is master or not.)

But for this case, you have to reorder the commits. Now I think it is easy to do:

- Reset to my master's HEAD or clone the repo to another place
- Seeing this pull request's diff, edit code and commit again. You should consider 3 points I wrote
- Force-push new local repo's master to your fork's master

**Comment by k0kubun** [comment]
Resolved by https://github.com/k0kubun/pp/pull/17.
Thank you for proposing a nice feature.

**Pull request closed without merging**
